#'
#' @description Filter dbsnp/non-dbsnp variants based on their normal depth
#'
#' @param rawmaf An MAF object, generated by \code{\link{vcfToMaf}} function
#' @param vcf_add A data frame contains the columns include and after 
#' the FORMAT column, come from the gt slot of a vcfR-class object
#' @param CSQ_info A data frame contains CSQ information extracted from VCF file 
#' and matches corresponding lines in MAF file, 
#' generated by \code{\link{getCSQ}} function
#' @param normalSampleName Label of the normal sample, should be one of the 
#' column names of parameter vcf_add
#' 
#'

mutFilterNormalDP <- function(rawmaf, vcf_add, CSQ_info, normalSampleName) {
  if (!('Existing_variation' %in% colnames(CSQ_info))) {
    stop('No annotation about existing database detected.')
  }
  
  # build a vector to store discarded variants
  discard <- c()
  
  for (i in 1:nrow(rawmaf)) {
    nDP_loc <- strsplit(vcf_add[i, 1], ":")[[1]] == 'DP'
    nDP <- as.numeric(strsplit(vcf_add[i, normalSampleName], ":")[[1]][nDP_loc])
    
    # variants in dbsnp
    if(str_detect(CSQ_info[i, 'Existing_variation'], 'rs')) {
      if(nDP < 19) {
        discard <- c(discard, i)
      }
      
      # variants not in dbsnp
    }else if (nDP < 8) {
      discard <- c(discard, i)
    }
  }
  
  if (is.null(discard)){
    message('Note: no mutation filtered for deficient normal depth.')
    return(list(rawmaf, vcf_add, CSQ_info))
  }else {
    maf <- rawmaf[-discard, ]
    vcf <- vcf_add[-discard, ]
    CSQ_f <- CSQ_info[-discard, ]
  }
  
  if (nrow(maf) == 0) {
    
    message('Note: no mutation left after normal depth filtering')
    return(list(maf, vcf, CSQ_f))
  } else {
    rownames(maf) <- 1:nrow(maf)
    rownames(CSQ_f) <- 1:nrow(CSQ_f)
    rownames(vcf) <- 1:nrow(vcf)
    return(list(maf, vcf, CSQ_f))
  }
  
}

