#' mutFilterAdj
#' @description Filter alleles based on adjacent indel tags
#'
#' @param maf An MAF data frame, generated by \code{\link{vcfToMAF}} function.
#' @param maxIndelLen Maximum length of indel accepted to be included.
#' Default: 50
#' @param minInterval Minimum length of interval between an SNV and an indel
#' accepted to be included. Default: 10
#'
#' @return An MAF data frame after filtration for adjacent alleles.
#'
#' @import dplyr
#'
#' @export mutFilterAdj
#' @examples
#' maf <- vcfToMAF(system.file("extdata", "GC48-2_mutect2.vep.vcf",
#' package = "CaMutQC"))
#' mafF <- mutFilterAdj(maf)


mutFilterAdj <- function(maf, maxIndelLen = 50, minInterval = 10){

  # sort and order variants in maf file
  mafFile <- arrange(maf, Chromosome, Start_Position)
  # mafFile$Start_Position <- as.numeric(mafFile$Start_Position)
  # mafFile$End_Position <- as.numeric(mafFile$End_Position)

  # calculate the distance between variants
  mafFile <- mafFile %>% group_by(Chromosome) %>%
    mutate(pre_diff = Start_Position - lag(Start_Position,
                                           default = Start_Position[1]),
           next_diff = End_Position - lag(End_Position,
                                          default = End_Position[1]))

  # filter variants
  n_tags <- rownames(mafFile[(nchar(mafFile$Reference_Allele)
                                    <= maxIndelLen) &
                        ((mafFile$pre_diff == 0 & mafFile$next_diff == 0) |
                        (mafFile$pre_diff >= minInterval &
                           mafFile$next_diff >= minInterval)), ])
  mafFile <- data.frame(mafFile)

  mafFile[!(rownames(mafFile) %in% n_tags), 'CaTag'] <-
    paste0(mafFile[!(rownames(mafFile) %in% n_tags), 'CaTag'] , 'A')

  return(subset(mafFile, select = c(-pre_diff, -next_diff)))
}

