#' mutFilterSB
#' @description Filter variants based on strand bias.
#'
#' @param maf An MAF object, generated by \code{\link{vcfToMAF}} function.
#' @param tumorSampleName Label of the tumor sample, should be one of the 
#' column names of maf. If it is set as 'Extracted', tumorSampleName would be
#' extracted automatically from the maf data frame. Default: 'Extracted'.
#' @param method Method will be used to detect strand bias, 
#' including 'SOR' and 'Fisher'. Default: 'SOR'. SOR: StrandOddsRatio 
#' (https://gatk.broadinstitute.org/hc/en-us/articles/360041849111-
#' StrandOddsRatio)
#' @param SBscore Cutoff strand bias score used to filter variants.
#' Default: 3
#' 
#' @return An MAF data frame where some variants 
#' has S tag in CaTag column for strand bias filtration
#' 
#' @export mutFilterSB
#'  

mutFilterSB <- function(maf, tumorSampleName = 'Extracted', 
                        method = 'SOR', SBscore = 3) {
  
  ## get tumorSampleName and normalSampleName
  if (tumorSampleName == 'Extracted'){
    tumorSampleName <- unique(maf$Tumor_Sample_Barcode)
  } else if(!(tumorSampleName %in% colnames(maf))) {
    stop('Invaild tumorSampleName.')
  }
  
  # use for loop to get the SB score for each variation
  if (method == 'Fisher') {
    for (i in seq_len(nrow(maf))) {
      SBindex <- strsplit(maf$FORMAT[i], ':')[[1]] == 'SB'
      if (all(SBindex == FALSE)){
        stop(paste0('No SB annotation found in FORMAT column, ', 
                    'so strand bias cannot be measured by Fisher exact test.'))
      }
      SBcharmatix <- strsplit(maf[i, tumorSampleName], 
                              ':')[[1]][SBindex]
      if (calSBscore(SBcharmatix, method) < SBscore) {
        maf[i, 'CaTag'] <- paste0(maf[i, 'CaTag'] , 'S')
      }
    }
  }else if (method == 'SOR'){
    for (i in seq_len(nrow(maf))) {
      F1R2index <- strsplit(maf$FORMAT[i], ':')[[1]] == 'F1R2'
      F2R1index <- strsplit(maf$FORMAT[i], ':')[[1]] == 'F2R1'
      F1R2 <- strsplit(maf[i, tumorSampleName], ':')[[1]][F1R2index]
      F2R1 <- strsplit(maf[i, tumorSampleName], ':')[[1]][F2R1index]
      SBcharmatix <- paste(F1R2, F2R1, sep = ',')
      if (calSBscore(SBcharmatix, method) > SBscore) {
        maf[i, 'CaTag'] <- paste0(maf[i, 'CaTag'] , 'S')
      }
    }
  }
    # maf[discard, 'CaTag'] <- paste0(maf[discard, 'CaTag'] , 'S')
    return(maf)
}

## construct function to calculate the SB score for strand bias detection
calSBscore <- function(charmatrix, method = 'SOR'){
  depths <- as.numeric(strsplit(charmatrix, ",")[[1]])
  if (method == 'SOR') {
    refFw <- depths[1] + 1
    refRv <- depths[3] + 1
    altFw <- depths[2] + 1
    altRv <- depths[4] + 1
    symmetricalRatio <- (refFw * altRv)/(refRv * altFw) + 
      (refRv * altFw) / (refFw * altRv)
    
    refRatio <- refRv / refFw
    altRatio <- altFw / altRv
    score <- log(symmetricalRatio) + log(refRatio) - log(altRatio)
    
  }else if (method == 'Fisher')   {
    refFw <- depths[1] 
    refRv <- depths[2]
    altFw <- depths[3]
    altRv <- depths[4]
    matrix <- rbind(c(refFw, refRv), c(altFw, altRv))
    score <- 1 - fisher.test(matrix)$p.value 
  }else {
    stop('Please select a method from SOR and Fisher')
  }
  
  return(score)
}
