#' mutFilterSNP
#' @description Filter SNP variants based on VAF and clinical significance
#'
#' @param maf An MAF data frame, generated by \code{\link{vcfToMAF}} function.
#' @param VAFcutoff Threshold of VAF value, variants with VAF lower than cutoff
#' will be filtered. Default: 0.05
#' 
#' @importFrom dplyr::filter
#' @return An MAF data frame after SNP filtering.

mutFilterSNP <- function(maf, VAFcutoff = 0.05) {
  
  ## filter variants
  maf_filtered <- dplyr::filter(maf, maf$VAF >= 0.05 | 
                           length(grep('athogenic', maf[, 'CLIN_SIG'])) != 0)
  
  
  if (nrow(maf_filtered) == 0){
    message('No mutation left after SNP filtering.')
  }else{
    rownames(maf_filtered) <- 1:nrow(maf_filtered)
  }
  return(maf_filtered)
}
