#'
#' @description Filter dbsnp/non-dbsnp variants based on their normal depth
#'
#' @param maf An MAF object, generated by \code{\link{vcfToMAF}} function.
#' @param normalSampleName Label of the normal sample, should be one of the 
#' column names of maf.
#' 
#' @return An MAF object after filtering for Normal depth

mutFilterNormalDP <- function(maf, normalSampleName) {
  if (!('Existing_variation' %in% colnames(maf))) {
    stop('No annotation about existing database detected.')
  }
  
  # build a vector to store discarded variants
  discard <- c()
  
  for (i in 1:nrow(maf)) {
    nDP_loc <- strsplit(maf[i, 'FORMAT'], ":")[[1]] == 'DP'
    nDP <- as.numeric(strsplit(maf[i, normalSampleName], ":")[[1]][nDP_loc])
    
    # variants in dbsnp
    if(length(grep('rs', l[, 'Existing_variation'])) != 0) {
      if(nDP < 19) {
        discard <- c(discard, i)
      }
      
      # variants not in dbsnp
    }else if (nDP < 8) {
      discard <- c(discard, i)
    }
  }
  
  if (is.null(discard)){
    message('Note: no mutation filtered for deficient normal depth.')
    return(maf)
  }else {
    maf_filtered <- maf[-discard, ]
  }
  
  if (nrow(maf_filtered) == 0) {
    
    message('Note: no mutation left after normal depth filtering')
    return(maf_filtered)
  } else {
    rownames(maf_filtered) <- 1:nrow(maf_filtered)
    return(maf_filtered)
  }
  
}

