#'
#' @description Filter variants based on strand bias
#'
#' @param rawmaf An MAF object, generated by \code{\link{vcfToMaf}} function
#' @param vcf_add A data frame contains the columns include and after 
#' the FORMAT column, come from the gt slot of a vcfR-class object
#' @param CSQ_info A data frame contains CSQ information extracted from VCF file 
#' and matches corresponding lines in MAF file, 
#' generated by \code{\link{getCSQ}} function
#' @param tumorSampleName Label of the tumor sample, should be one of the 
#' column names of parameter vcf_add
#' @param method Method will be used to detect strand bias, 
#' including 'SOR' and 'Fisher'. Default: 'SOR'
#' @param threshold Cutoff strand bias value will be used to filter variants.
#' Default: 3
#'

mutFilterSB <- function(rawmaf, vcf_add, CSQ_info, tumorSampleName,
                        method = 'SOR', threshold = 3) {
  withoutSB <- sum(!(str_detect(vcf_add$FORMAT, 'SB')))
  message(paste0(withoutSB, ' row(s) of information doesn\'t have SB information.'))
  discard <- c()
  
  # use for loop to get the SB score for each variation
  for (i in 1:nrow(rawmaf)){
    if (!(i %in% withoutSB)) {
      SBindex <- strsplit(vcf_additional$FORMAT[i], ':')[[1]] == 'SB'
      SBcharmatix <- strsplit(vcf_additional[i, tumorSampleName], 
                              ':')[[1]][SBindex]
      if (SBscore(SBcharmatix, method) > threshold) {
        discard <- c(discard, i)
      }
    }
  }
  
  if (is.null(discard)){
    message('Note: no mutation filtered for Strand Bias.')
    return(list(rawmaf, vcf_add, CSQ_info))
  }else {
    maf <- rawmaf[-discard, ]
    vcf <- vcf_add[-discard, ]
    CSQ_f <- CSQ_info[-discard, ]
  }
  
  if (nrow(maf) == 0) {
    
    message('Note: no mutation left after Strand Bias filtering.')
    return(list(maf, vcf, CSQ_f))
  } else {
    rownames(maf) <- 1:nrow(maf)
    rownames(CSQ_f) <- 1:nrow(CSQ_f)
    rownames(vcf) <- 1:nrow(vcf)
    return(list(maf, vcf, CSQ_f))
  }
  
}

## write function to calculate the SB score for strand bias detection
SBscore <- function(charmatrix, method = 'SOR'){
  depths <- as.numeric(strsplit(charmatrix, ",")[[1]])
  refFw <- depths[1] + 1
  refRv <- depths[2] + 1
  altFw <- depths[3] + 1
  altRv <- depths[4] + 1
  
  if (method == 'SOR') {
    symmetricalRatio <- (refFw * altRv)/(refRv * altFw) + 
      (refRv * altFw) / (refFw * altRv)
    
    refRatio <- refRv / refFw
    altRatio <- altFw / altRv
    score <- log(symmetricalRatio) + log(refRatio) - log(altRatio)
    
  }else if (method == 'Fisher')   {
    matrix <- rbind(c(refFw, refRv), c(altFw, altRv))
    score <- 1 - fisher.test(matrix)$p.value 
  }else {
    stop('Please select a method from SOR and Fisher')
  }
  
  return(score)
}
