#'
#' @description Filter variants not in COSMIC
#'
#' @param maf An MAF object, generated by \code{\link{vcfToMAF}} function.
#' 
#' @return An MAF object after COSMIC filtering

mutFilterCOSMIC <- function(maf) {
  
    if ('Existing_variation' %in% colnames(maf)) {
    
    maf_filtered <- data.frame(maf[grep('COSV', maf[, 'Existing_variation']), ])
    
    if (nrow(maf_filtered) == 0) {
      
      message('Note: no mutation left after COSMIC filtering')
      return(maf_filtered)
    } else if (nrow(maf) == nrow(maf_filtered)) {
      message('Note: no mutation filtered.')
    } else {
      rownames(maf_filtered) <- 1:nrow(maf_filtered)
      return(maf_filtered)
    }
    
  } else {
    message('VCF file hasn\'t been annotated by VEP, 
            so no variation was filtered')
    return(maf_filtered)
  }
}
