#' mutFilterSNP
#' @description Filter SNP variants based on VAF and clinical significance
#'
#' @param maf An MAF data frame, generated by \code{\link{vcfToMAF}} function.
#' @param VAFcutoff Threshold of VAF value, variants with VAF lower than cutoff
#' will be filtered. Default: 0.05
#' 
#' @importFrom dplyr::filter
#' @return An MAF data frame after SNP filtration.
#' 
#' @export mutFilterSNP

mutFilterSNP <- function(maf, VAFcutoff = 0.05) {
  
  ## filter variants
  maf_filtered <- dplyr::filter(maf, (maf$VAF >= 0.05 & 
                                        maf$Variant_Type == 'SNP') | 
                           length(grep('athogenic', maf[, 'CLIN_SIG'])))
  
  
  if (nrow(maf_filtered) == 0){
    message('No mutation left after SNP filtration.')
  }else{
    rownames(maf_filtered) <- seq_len(nrow(maf_filtered))
  }
  return(maf_filtered)
}
