#'
#' @description Filter variants not in COSMIC
#'
#' @param rawmaf An MAF object, generated by \code{\link{vcfToMaf}} function
#' @param vcf_add A data frame contains the columns include and after 
#' the FORMAT column, come from the gt slot of a vcfR-class object
#' @param CSQ_info A data frame contains CSQ information extracted from VCF file 
#' and matches corresponding lines in MAF file, 
#' generated by \code{\link{getCSQ}} function
#' 
#'

mutFilterCOSMIC <- function(rawmaf, vcf_add, CSQ_info) {
  
  # check the length of maf file and CSQ info
  #if (nrow(rawmaf) != nrow(CSQ_info)) {
  #stop('The length of maf file and CSQ info failed to match')
  #}
  
  # select variants annotated by VEP through COSMIC
  if ('Existing_variation' %in% colnames(CSQ_info)) {
    
    maf <- data.frame(rawmaf[str_detect(CSQ_info[, 'Existing_variation'], 
                                        pattern = 'COSV'), ])
    CSQ_f <- data.frame(CSQ_info[str_detect(CSQ_info[, 'Existing_variation'], 
                                            pattern = 'COSV'), ])
    vcf <- data.frame(vcf_add[str_detect(CSQ_info[, 'Existing_variation'], 
                                         pattern = 'COSV'), ])
    
    if (nrow(maf) == 0) {
      
      message('Note: no mutation left after COSMIC filtering')
      return(list(maf, vcf, CSQ_f))
    } else {
      rownames(maf) <- 1:nrow(maf)
      rownames(CSQ_f) <- 1:nrow(CSQ_f)
      rownames(vcf) <- 1:nrow(vcf)
      return(list(maf, vcf, CSQ_f))
    }
    
  } else {
    message('VCF file hasn\'t been annotated by VEP, 
            so no variation was filtered')
    return(list(rawmaf, vcf_add, CSQ_info))
  }
}
