#' mutFilterCOSMIC
#' @description Filter variants not in COSMIC
#'
#' @param maf An MAF data frame, generated by \code{\link{vcfToMAF}} function.
#' 
#' @return An MAF data frame after COSMIC filtering
#' 
#' @export mutFilterCOSMIC

mutFilterCOSMIC <- function(maf) {
  
    if ('Existing_variation' %in% colnames(maf)) {
    
      maf_filtered <- as.data.frame(maf[grep('COS', maf[, 
                                                      'Existing_variation']), ])
    
      
      if (nrow(maf_filtered) == 0){
        message('No mutation left after COSMIC filtering.')
      }else{
        rownames(maf_filtered) <- 1:nrow(maf_filtered)
      }
      return(maf_filtered)
  } else {
    return(maf)
  }
}
