#' mutFilterType
#' @description Filter variants of certain types
#'
#' @param maf An MAF data frame, generated by \code{\link{vcfToMAF}} function.
#' @param keepType A group of variant classifications will be kept, 
#' including 'exonic' and 'nonsynonymous'. Default: 'exonic'. 
#' 
#' @return An MAF data frame where some variants 
#' has T tag in CaTag column for variant type filtration
#' 
#' @export mutFilterType

mutFilterType <- function(maf, keepType = 'exonic') {
  
  # process keepType
  if (keepType == 'exonic') {
    keepType <- c('RNA', 'Intron', 'IGR', '5\'Flank', '3\'Flank', 
               '5\'UTR', '3\'UTR')
  } else if (keepType == 'nonsynonymous') {
    keepType <- c("3'UTR", "5'UTR", "3'Flank", "Targeted_Region", "Silent", 
               "Intron", "RNA", "IGR", "Splice_Region", "5'Flank", "lincRNA", 
               "De_novo_Start_InFrame", "De_novo_Start_OutOfFrame", 
               "Start_Codon_Ins", "Start_Codon_SNP", "Stop_Codon_Del")
  } else {
    stop('Please select one category of types from exonic and nonsynonymous.')
  }
  
  # add T tag
  tags <- rownames(maf[maf$Variant_Classification %in% keepType, ])
  maf[tags, 'CaTag'] <- paste0(maf[tags, 'CaTag'], 'T')

  return(maf)
}
