#' mutSelection
#' @description Select candidate variants for cancer research.
#'
#' @param maf An MAF data frame, generated by \code{\link{vcfToMAF}} function.
#' @param dbVAF Threshold of VAF of certain population for variants
#'  in database. Default: 0.01
#' @param ExAC Whether to filter variants listed in ExAC with VAF higher than
#' cutoff(set in VAF parameter). Default: TRUE.
#' @param Genomesprojects1000 Whether to filter variants listed in 
#' Genomesprojects1000 with VAF higher than cutoff(set in VAF parameter). 
#' Default: TRUE.
#' @param ESP6500 Whether to filter variants listed in ESP6500 with VAF higher 
#' than cutoff(set in VAF parameter). Default: TRUE.
#' @param gnomAD Whether to filter variants listed in gnomAD with VAF higher 
#' than cutoff(set in VAF parameter). Default: TRUE.
#' @param dbSNP Whether to filter variants listed in dbSNP. Default: FALSE.
#' @param COSMIConly Whether to only keep variants in COSMIC. Default: FALSE.
#' @param keepType A group of variant classifications will be kept, 
#' including 'exonic', 'nonsynonymous' and 'ALL'. Default: 'exonic'. 
#' @param bedFile A file in bed format that contains region information.
#' Default: NULL
#' @param bedFilter Whether to filter the information in bed file or not, which 
#' only leaves segments in Chr1-Ch22, ChrX and ChrY. Default: TRUE
#' 
#' @import vcfR, stringr, dplyr::filter
#' 
#' @return An MAF data frame with variants after selection.
#' 
#' @export mutSelection


mutSelection <- function(maf, dbVAF = 0.01, ExAC = TRUE, 
                         Genomesprojects1000 = TRUE, ESP6500 = TRUE, 
                         gnomAD = TRUE, dbSNP = FALSE, 
                         COSMIConly = TRUE, keepType = 'exonic',
                         bedFile = NULL, bedFilter = TRUE){
  
  # database selection
  message('Selection for germline variant database is in process.')
  maf <- mutFilterDB(maf, VAF = dbVAF, ExAC = ExAC, 
                     Genomesprojects1000 = Genomesprojects1000, ESP6500 = ESP6500,
                     gnomAD = gnomAD, dbSNP = dbSNP, COSMIConly = COSMIConly)
  
  # variant type selection
  message('Selection for variant type is in process.')
  maf <- mutFilterType(maf, keepType = keepType)
  
  # normal DP selection
  message('Selection for normal DP is in process.')
  maf <- mutFilterNormalDP(maf)
  
  # PON selection 
  message('Selection for panel of normals is in process.')
  maf <- mutFilterPON(maf)
  
  # region selection
  message('Selection for variants in specific region is in process.')
  maf <- mutFilterReg(maf, bedFile = bedFile, bedFilter = bedFilter)
  
  # complete selection
  message('Cancer variant selection is done!')
  return(maf)
}


